int evilRaySystemProcessType = FIRST_PROCESS_TYPE+0;
int fieryTailSystemProcessType = FIRST_PROCESS_TYPE+1;
int streakSystemProcessType = FIRST_PROCESS_TYPE+2;
int ropeSystemProcessType = FIRST_PROCESS_TYPE+3;
int burningSystemProcessType = FIRST_PROCESS_TYPE+4;
int kaboomSystemProcessType = FIRST_PROCESS_TYPE+5;
int flyingShrapnelSystemProcessType = FIRST_PROCESS_TYPE+6;
int buildSystemProcessType = FIRST_PROCESS_TYPE+7;
int dissolveSystemProcessType = FIRST_PROCESS_TYPE+8;
int lightningSystemProcessType = FIRST_PROCESS_TYPE+9;
int beamOverSystemProcessType = FIRST_PROCESS_TYPE+10;
int smokeSystemProcessType = FIRST_PROCESS_TYPE+11;
int fountainSystemProcessType = FIRST_PROCESS_TYPE+12;
int teleportEffectProcessType = FIRST_PROCESS_TYPE+13;
int dudeProcessType = FIRST_PROCESS_TYPE+14;
int canonRealizeProcessType = FIRST_PROCESS_TYPE+15;
int rookAttackProcessType = FIRST_PROCESS_TYPE+16;
int targetProcessType = FIRST_PROCESS_TYPE+17;
int missileProcessType = FIRST_PROCESS_TYPE+18;
int pingPongProcessType = FIRST_PROCESS_TYPE+19;
int constructionProcessType = FIRST_PROCESS_TYPE+20;
int baseFlyerProcessType = FIRST_PROCESS_TYPE+21;
int sunAviaryProcessType = FIRST_PROCESS_TYPE+22;
int islandDropperProcessType = FIRST_PROCESS_TYPE+23;
int gunProcessType = FIRST_PROCESS_TYPE+24;
int fireAnimProcessType = FIRST_PROCESS_TYPE+25;
int rotateAnimProcessType = FIRST_PROCESS_TYPE+26;
int scrollTestProcessType = FIRST_PROCESS_TYPE+27;
int simpleWalkerProcessType = FIRST_PROCESS_TYPE+28;
int simpleFlyProcessType = FIRST_PROCESS_TYPE+29;
int wormProcessType = FIRST_PROCESS_TYPE+30;
int bulfProcessType = FIRST_PROCESS_TYPE+31;
int balloonProcessType = FIRST_PROCESS_TYPE+32;
int ambleProcessType = FIRST_PROCESS_TYPE+33;
int driftProcessType = FIRST_PROCESS_TYPE+34;
int rainVortexAnimProcessType = FIRST_PROCESS_TYPE+35;
int regularProcessType = FIRST_PROCESS_TYPE+36;
int soundProcessType = FIRST_PROCESS_TYPE+37;
int windBatteryProcessType = FIRST_PROCESS_TYPE+38;
int buildPlaybackProcessType = FIRST_PROCESS_TYPE+39;
int manaDisplayProcessType = FIRST_PROCESS_TYPE+40;
int rangeDisplayProcessType = FIRST_PROCESS_TYPE+41;
int islandAnimatorProcessType = FIRST_PROCESS_TYPE+42;
int cameraAnimatorProcessType = FIRST_PROCESS_TYPE+43;
int priestProcessType = FIRST_PROCESS_TYPE+44;
int paletteFlasherProcessType = FIRST_PROCESS_TYPE+45;
int thunderArcherSystemProcessType = FIRST_PROCESS_TYPE+46;
int bombEffectTimerProcessType = FIRST_PROCESS_TYPE+47;
int daisProcessType = FIRST_PROCESS_TYPE+48;
int windAviaryProcessType = FIRST_PROCESS_TYPE+49;
int rainAviaryProcessType = FIRST_PROCESS_TYPE+50;
int sharedRegularProcessType = FIRST_PROCESS_TYPE+51;
int ThunderAviaryProcessType = FIRST_PROCESS_TYPE+52;
int RainFenceProcessType = FIRST_PROCESS_TYPE+53;
int numProcessTypes = FIRST_PROCESS_TYPE+54;

int dudeType = FIRST_GENERATED_REAL_TYPE+0;
int sunArcherType = FIRST_GENERATED_REAL_TYPE+1;
int sunAviaryType = FIRST_GENERATED_REAL_TYPE+2;
int sunFlyerType = FIRST_GENERATED_REAL_TYPE+3;
int bannerType = FIRST_GENERATED_REAL_TYPE+4;
int windBatteryType = FIRST_GENERATED_REAL_TYPE+5;
int rainBatteryType = FIRST_GENERATED_REAL_TYPE+6;
int thunderBatteryType = FIRST_GENERATED_REAL_TYPE+7;
int sunBlockerType = FIRST_GENERATED_REAL_TYPE+8;
int thunderBlockerType = FIRST_GENERATED_REAL_TYPE+9;
int blankMissileType = FIRST_GENERATED_REAL_TYPE+10;
int boltType = FIRST_GENERATED_REAL_TYPE+11;
int bridgeType = FIRST_GENERATED_REAL_TYPE+12;
int sunDiscType = FIRST_GENERATED_REAL_TYPE+13;
int emptyGeyserType = FIRST_GENERATED_REAL_TYPE+14;
int sunFactoryType = FIRST_GENERATED_REAL_TYPE+15;
int windFactoryType = FIRST_GENERATED_REAL_TYPE+16;
int rainFactoryType = FIRST_GENERATED_REAL_TYPE+17;
int thunderFactoryType = FIRST_GENERATED_REAL_TYPE+18;
int residenceType = FIRST_GENERATED_REAL_TYPE+19;
int fencemarkType = FIRST_GENERATED_REAL_TYPE+20;
int flagType = FIRST_GENERATED_REAL_TYPE+21;
int fortGumpType = FIRST_GENERATED_REAL_TYPE+22;
int iconType = FIRST_GENERATED_REAL_TYPE+23;
int islandType = FIRST_GENERATED_REAL_TYPE+24;
int islandStalagType = FIRST_GENERATED_REAL_TYPE+25;
int playerBannerType = FIRST_GENERATED_REAL_TYPE+26;
int isleType = FIRST_GENERATED_REAL_TYPE+27;
int isleBigType = FIRST_GENERATED_REAL_TYPE+28;
int geyserBrightenerType = FIRST_GENERATED_REAL_TYPE+29;
int treeTwoType = FIRST_GENERATED_REAL_TYPE+30;
int treeThreeType = FIRST_GENERATED_REAL_TYPE+31;
int fringeType = FIRST_GENERATED_REAL_TYPE+32;
int manaType = FIRST_GENERATED_REAL_TYPE+33;
int rangeType = FIRST_GENERATED_REAL_TYPE+34;
int manaboltType = FIRST_GENERATED_REAL_TYPE+35;
int flareType = FIRST_GENERATED_REAL_TYPE+36;
int puzzlePieceType = FIRST_GENERATED_REAL_TYPE+37;
int playerIslandType = FIRST_GENERATED_REAL_TYPE+38;
int battleIslandType = FIRST_GENERATED_REAL_TYPE+39;
int particlePlaceHolderType = FIRST_GENERATED_REAL_TYPE+40;
int sunBalloonType = FIRST_GENERATED_REAL_TYPE+41;
int buriedType = FIRST_GENERATED_REAL_TYPE+42;
int bombExplodeSmallType = FIRST_GENERATED_REAL_TYPE+43;
int bombExplodeMediumType = FIRST_GENERATED_REAL_TYPE+44;
int bombExplodeLargeType = FIRST_GENERATED_REAL_TYPE+45;
int bombHealType = FIRST_GENERATED_REAL_TYPE+46;
int bombInvisibleType = FIRST_GENERATED_REAL_TYPE+47;
int bombParalyzeType = FIRST_GENERATED_REAL_TYPE+48;
int bombHardenerType = FIRST_GENERATED_REAL_TYPE+49;
int bombTreasonType = FIRST_GENERATED_REAL_TYPE+50;
int edgeFarmType = FIRST_GENERATED_REAL_TYPE+51;
int geyserType = FIRST_GENERATED_REAL_TYPE+52;
int windVortexType = FIRST_GENERATED_REAL_TYPE+53;
int rainVortexType = FIRST_GENERATED_REAL_TYPE+54;
int thunderVortexType = FIRST_GENERATED_REAL_TYPE+55;
int outpostType = FIRST_GENERATED_REAL_TYPE+56;
int mcloudType = FIRST_GENERATED_REAL_TYPE+57;
int sunCannonType = FIRST_GENERATED_REAL_TYPE+58;
int rainCannonType = FIRST_GENERATED_REAL_TYPE+59;
int rainCannonMissileType = FIRST_GENERATED_REAL_TYPE+60;
int thunderCannonType = FIRST_GENERATED_REAL_TYPE+61;
int thunderCannonMissileType = FIRST_GENERATED_REAL_TYPE+62;
int sunWalkerType = FIRST_GENERATED_REAL_TYPE+63;
int teleportEffectType = FIRST_GENERATED_REAL_TYPE+64;
int bulfType = FIRST_GENERATED_REAL_TYPE+65;
int sunFenceType = FIRST_GENERATED_REAL_TYPE+66;
int windWalkerType = FIRST_GENERATED_REAL_TYPE+67;
int windFlyerType = FIRST_GENERATED_REAL_TYPE+68;
int windAviaryType = FIRST_GENERATED_REAL_TYPE+69;
int windArcherType = FIRST_GENERATED_REAL_TYPE+70;
int windBalloonType = FIRST_GENERATED_REAL_TYPE+71;
int windBlockerType = FIRST_GENERATED_REAL_TYPE+72;
int rainAviaryType = FIRST_GENERATED_REAL_TYPE+73;
int rainFlyerType = FIRST_GENERATED_REAL_TYPE+74;
int rainFenceType = FIRST_GENERATED_REAL_TYPE+75;
int rainBalloonType = FIRST_GENERATED_REAL_TYPE+76;
int rainBlockerType = FIRST_GENERATED_REAL_TYPE+77;
int thunderArcherType = FIRST_GENERATED_REAL_TYPE+78;
int thunderFenceType = FIRST_GENERATED_REAL_TYPE+79;





int growingRainBlockerType = FIRST_GENERATED_REAL_TYPE+80;
int platformType = FIRST_GENERATED_REAL_TYPE+81;
int playerType = FIRST_GENERATED_REAL_TYPE+82;
int mogType = FIRST_GENERATED_REAL_TYPE+83;
int nuggetType = FIRST_GENERATED_REAL_TYPE+84;
int bridgeConnectorType = FIRST_GENERATED_REAL_TYPE+85;
int rainWalkerType = FIRST_GENERATED_REAL_TYPE+86;
int noIslandType = FIRST_GENERATED_REAL_TYPE+87;
int priestType = FIRST_GENERATED_REAL_TYPE+88;

#define UINTUPDATEBY 3
int windWhirlType=FIRST_GENERATED_REAL_TYPE+89;
int RUINType=FIRST_GENERATED_REAL_TYPE+90;
int MonumentType=FIRST_GENERATED_REAL_TYPE+91;
//int GuildFactoryType=FIRST_GENERATED_REAL_TYPE+92;




int lightningType = FIRST_GENERATED_REAL_TYPE+89+UINTUPDATEBY;
int animType = FIRST_GENERATED_REAL_TYPE+90+UINTUPDATEBY;
int challengeIslandType = FIRST_GENERATED_REAL_TYPE+91+UINTUPDATEBY;
int fakeThreeByThreeSurfaceType = FIRST_GENERATED_REAL_TYPE+92+UINTUPDATEBY;
int sunFlyerBombType = FIRST_GENERATED_REAL_TYPE+93+UINTUPDATEBY;
int altarType = FIRST_GENERATED_REAL_TYPE+94+UINTUPDATEBY;
int daisType = FIRST_GENERATED_REAL_TYPE+95+UINTUPDATEBY;
int runeType = FIRST_GENERATED_REAL_TYPE+96+UINTUPDATEBY;
int forceFieldType = FIRST_GENERATED_REAL_TYPE+97+UINTUPDATEBY;
int bombSpecialOneType = FIRST_GENERATED_REAL_TYPE+98+UINTUPDATEBY;
int daisExtraFramesType = FIRST_GENERATED_REAL_TYPE+99+UINTUPDATEBY;
// 70 patch additions!
int fenceShieldType = FIRST_GENERATED_REAL_TYPE+100+UINTUPDATEBY;
int bombTwisterType=FIRST_GENERATED_REAL_TYPE+101+UINTUPDATEBY;
int bombTwister2Type=FIRST_GENERATED_REAL_TYPE+102+UINTUPDATEBY;
int bombTwister3Type=FIRST_GENERATED_REAL_TYPE+103+UINTUPDATEBY;
int gravitationEffectType = FIRST_GENERATED_REAL_TYPE+104+UINTUPDATEBY;
int bombgravitationType=FIRST_GENERATED_REAL_TYPE+105+UINTUPDATEBY;
int HealEffectType=FIRST_GENERATED_REAL_TYPE+106+UINTUPDATEBY;
int meteoreffectType=FIRST_GENERATED_REAL_TYPE+107+UINTUPDATEBY;
int bombmeteorType=FIRST_GENERATED_REAL_TYPE+108+UINTUPDATEBY;

int bombMano1Type=FIRST_GENERATED_REAL_TYPE+109+UINTUPDATEBY;
int bombMano2Type=FIRST_GENERATED_REAL_TYPE+110+UINTUPDATEBY;
int bombMano3Type=FIRST_GENERATED_REAL_TYPE+111+UINTUPDATEBY;

int bombLightingZapType=FIRST_GENERATED_REAL_TYPE+112+UINTUPDATEBY;
int bombLightingwaveType=FIRST_GENERATED_REAL_TYPE+113+UINTUPDATEBY;




//int skygullType = FIRST_GENERATED_REAL_TYPE+101+UINTUPDATEBY;
int numTypes = FIRST_GENERATED_REAL_TYPE+118+UINTUPDATEBY;
// Riftedskies update by fleet
//int numTypes = FIRST_GENERATED_REAL_TYPE+102;
